export { useCasePages } from "./use-cases"
export { industryPages } from "./industries"
export { personaPages } from "./personas"
export { blogPosts } from "./blog-posts"
export { resources } from "./resources"
export type { LandingPage, BlogPost, Resource } from "./types"
