import { type NextRequest, NextResponse } from "next/server"
import { resources } from "@/lib/content/resources"

export async function GET(request: NextRequest) {
  const slug = request.nextUrl.searchParams.get("slug")
  if (!slug) {
    return NextResponse.json({ error: "Missing slug parameter" }, { status: 400 })
  }

  const resource = resources.find((r) => r.slug === slug)
  if (!resource) {
    return NextResponse.json({ error: "Resource not found" }, { status: 404 })
  }

  // Generate a plain text version formatted for PDF-like reading
  const header = `${"=".repeat(60)}
${resource.title.toUpperCase()}
${"=".repeat(60)}

Type: ${resource.type.charAt(0).toUpperCase() + resource.type.slice(1)}
Pages: ${resource.pages}
Category: ${resource.category}

${resource.longDescription}

${"=".repeat(60)}

`

  const footer = `

${"=".repeat(60)}
Generated by Core Model - Evidence-Based Adaptive Learning
https://coremodel.app

Topics covered: ${resource.topics.join(", ")}
${"=".repeat(60)}
`

  const fullContent = header + resource.content + footer

  return new NextResponse(fullContent, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${resource.slug}.txt"`,
    },
  })
}
