import { eq } from "drizzle-orm";
import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { db } from "@/db";
import { user } from "@/db/schema";
import { auth } from "@/lib/auth";

const ADMIN_EMAILS = ["admin@coremodel.ai"];

function isAdminEmail(email: string): boolean {
  if (ADMIN_EMAILS.includes(email)) return true;
  // In dev mode, allow admin-*.coremodel.ai emails (generated by dev quick login)
  if (
    process.env.NODE_ENV === "development" &&
    /^admin-.+@coremodel\.ai$/.test(email)
  )
    return true;
  return false;
}

export async function POST() {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session)
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  if (isAdminEmail(session.user.email)) {
    await db
      .update(user)
      .set({ role: "admin" })
      .where(eq(user.id, session.user.id));

    return NextResponse.json({ role: "admin" });
  }

  return NextResponse.json({ role: "user" });
}
